### ISSUE TITLE
Parks and cultures wrong shape 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Paris#18] opened 2020-04-08 14:06 UTC
Original 
<img width="1148" alt="Screen Shot 2020-04-08 at 16 01 12" src="https://user-images.githubusercontent.com/3928502/78793118-3fd0a780-79b2-11ea-991f-bc29a37c5efb.png">
webgl
<img width="1864" alt="Screen Shot 2020-04-08 at 16 00 38" src="https://user-images.githubusercontent.com/3928502/78793140-465f1f00-79b2-11ea-8f4e-e769bf048813.png">

Which might raise this issue on the spot #9 but let's see later.

**Comment by LAAP** [comment] 2020-04-08 17:44
I do not dislike that much the webgl rendering... It has a lack of accuracy in the shades, but if that can be fixed, then it is a bit playing with the "palette of colors". Can we play with it?

**Comment by agrignard** [comment] 2020-04-08 18:00
I was actually not speaking about the color ;-) (it's a too sensitive topics) but the shapes

**Comment by LAAP** [comment] 2020-04-08 18:40
In my opinion, shapes are OK, as a starting point.

**Comment by agrignard** [comment] 2020-04-08 21:03
@LAAP until you find your glasses today here is a zoom and a super zoom ;-)
original
<img width="1154" alt="Screen Shot 2020-04-08 at 22 57 36" src="https://user-images.githubusercontent.com/3928502/78833034-8216da80-79ec-11ea-836c-77f59f15eca9.png">
webgl
<img width="702" alt="Screen Shot 2020-04-08 at 22 58 21" src="https://user-images.githubusercontent.com/3928502/78833056-8cd16f80-79ec-11ea-81e1-2a8335bb6098.png">

original
<img width="308" alt="Screen Shot 2020-04-08 at 23 01 50" src="https://user-images.githubusercontent.com/3928502/78833350-023d4000-79ed-11ea-9bbe-770c209fe73a.png">
webgl
<img width="179" alt="Screen Shot 2020-04-08 at 23 02 01" src="https://user-images.githubusercontent.com/3928502/78833355-04070380-79ed-11ea-8e3a-328f570b70bc.png">

**Comment by agrignard** [comment] 2020-04-10 10:37
I don't what is the process here to produce the shape and to fix them. Not sure if it makes sense to push all the difference but just in case here a some of them


<img width="339" alt="Screen Shot 2020-04-10 at 12 31 12" src="https://user-images.githubusercontent.com/3928502/78984781-66fcb580-7b27-11ea-912c-9ce65cbc5c16.png">

<img width="451" alt="Screen Shot 2020-04-10 at 12 36 23" src="https://user-images.githubusercontent.com/3928502/78984982-f013ec80-7b27-11ea-8703-2a078016c22f.png">

**Comment by RELNO** [comment] 2020-04-10 15:26
see #16. this won't be fixed until we have one set of objects exported the same way.

**Comment by agrignard** [comment] 2020-04-10 15:35
But City, Park and Cultural are exported in the same aren't they?

**Comment by LAAP** [comment] 2020-04-10 18:45
Do not get me wrong, I know that it is not "Perfect" rendering, However it is a fantastic starting point.

From my lack of knowledge, this reminds me a bit of my first years making 3Ds and exporting from AutoCad to 3D MAX. When using DWG format for exporting, some nodes where missing (exactly same effect than in this model), when using txt format, the exported file was working much better.  I Wonder if this could be happening here somehow?

**Comment by agrignard** [comment] 2020-04-10 22:04
we are working with @tnguyenh that created a buildings.obj created from buildings.shp on blender (there still the building with holes to handle but at least we can check if it fits better

here
https://github.com/CityScope/CSL_Paris/tree/master/ReChamp_Gama/includes/GIS/obj

**Comment by RELNO** [comment] 2020-04-12 09:56
When loading `buildings.obj` it looks like only the yards are created 
![Screen Shot 2020-04-12 at 05 54 49](https://user-images.githubusercontent.com/14296774/79065979-4dbc4c00-7c82-11ea-86bc-6ecd769e0e6f.png)
![Screen Shot 2020-04-12 at 05 55 37](https://user-images.githubusercontent.com/14296774/79065980-4dbc4c00-7c82-11ea-8e61-ee53ea66e232.png)

**Comment by tnguyenh** [comment] 2020-04-12 15:08
OK I think I committed an intermediate version of the .obj and not the right one, the tall building-like objects should not be there and there shouldn't be any wall missing... try the current one...

**Comment by tnguyenh** [comment] 2020-04-12 15:09
However the shapes look odd... what programm do you use ?

**Comment by tnguyenh** [comment] 2020-04-12 15:11
It should look like that:

![image](https://user-images.githubusercontent.com/18676913/79072295-93a7fd00-7ce0-11ea-9714-6e2e51239beb.png)

Btw we should do a proper Arc de Triomphe...

**Comment by RELNO** [comment] 2020-04-12 16:35
> However the shapes look odd... what programm do you use ?

THREEjs. What is the scale it's exported with? Does it already fit the table scale in meters? 

> Btw we should do a proper Arc de Triomphe...

I thought that's how it looks apres des gilets jaunes..

**Comment by agrignard** [comment] 2020-04-13 13:43
I guess it's a question of scale. From what I know @tnguyenh imported it in blender and then exported it in a .obj

I would say that playing with this should be fine as 0.0005 is 1/2000? 

`````
model.scale.set(0.000505, 0.000505, 0.000505);
    model.position.set(-0.0055, 0.7, 0);
    model.rotation.set(0, 0.4625123, 0);
``````

@RELNO how does it look so far?

**Comment by LAAP** [comment] 2020-04-13 14:17
It is looking good. I agree with @tnguyenh , we need the real Arc de Triomphe

**Comment by RELNO** [comment] 2020-04-13 14:27
There are a bit too many conversions, so I'll try to simplify: 
Looks like Tri and I are doing the same (qgis shp => blender using GIS import => JS). This is how I got the city model in the first place, so I don't see a difference.
What I still need is that all the other layers will be exported exactly the same way and in the same scale. So that when I import, I can use one scale/location for all instead of messing with each layer. 

> I would say that playing with this should be fine as 0.0005 is 1/2000?

For only the city model. Not for the parks etc.

**Comment by agrignard** [comment] 2020-04-13 14:45
The parks and culture have not been created yet as we need first to fix the 3D city model no?

**Comment by tnguyenh** [comment] 2020-04-13 17:49
Hi guys, I don't really understand where is the problem since I haven't followed the story from the beginning. Right now it is clear that there is a problem with the final render: 


> 
> 
> @LAAP until you find your glasses today here is a zoom and a super zoom ;-)
> original
> <img alt="Screen Shot 2020-04-08 at 22 57 36" width="1154" src="https://user-images.githubusercontent.com/3928502/78833034-8216da80-79ec-11ea-836c-77f59f15eca9.png">
> webgl
> <img alt="Screen Shot 2020-04-08 at 22 58 21" width="702" src="https://user-images.githubusercontent.com/3928502/78833056-8cd16f80-79ec-11ea-81e1-2a8335bb6098.png">
> 
> original
> <img alt="Screen Shot 2020-04-08 at 23 01 50" width="308" src="https://user-images.githubusercontent.com/3928502/78833350-023d4000-79ed-11ea-9bbe-770c209fe73a.png">
> webgl
> <img alt="Screen Shot 2020-04-08 at 23 02 01" width="179" src="https://user-images.githubusercontent.com/3928502/78833355-04070380-79ed-11ea-8e3a-328f570b70bc.png">



As far as I can see, (1) the buildings shapes are odd, some vertices and faces are missing, holes haven't been processed correctly and (2), maybe there are some surfaces overlapping (same z), like the parks on Champs Elysées. 

For point (1):  with start with .shp, convert it to .obj, then to JS. We all have the same .shp. From the picture you posted Ariel, I guess that the problem is with the .obj file (wrong polygon topology) and I assume you don't do any special transformation with JS (scaling and translating should not be a harmful transformation).

Try the latest version of the .obj in order to see first if it is working (not the one you did some screenshot with, there is also a topology problem with it).

For point (2), add a small z to the shapes...

**Comment by RELNO** [comment] 2020-04-13 17:56
@tnguyenh thanks, let's find a few minutes to skype/zoom/fax about it?

**Comment by tnguyenh** [comment] 2020-04-13 17:57
Yes ok !

**Comment by RELNO** [comment] 2020-04-15 13:18
To do: @tnguyenh @agrignard @RELNO to meet and export all layers at the same scale/rotation/z-height.

**Comment by tnguyenh** [comment] 2020-04-15 14:09
OK, I think I've understood what is the problem. I exported to .obj and vizualised it, and the mesh wasn't clean. Try the new version, the problem should be solved now.

The reason is that most programs don't support non-convex polygons (but blender does). So the solution is just to split non-convex polygons in blender.

**Comment by agrignard** [comment] 2020-04-15 14:13
so this one has been updated
https://github.com/CityScope/CSL_Paris/blob/master/ReChamp_Gama/includes/GIS/obj/buildings.obj

**Comment by tnguyenh** [comment] 2020-04-15 14:16
yep

**Comment by RELNO** [comment] 2020-04-18 17:31
@agrignard does `CSL_Paris/ReChamp_Gama/includes/GIS/obj`holds the last version? there's only buildings and culture

**Comment by agrignard** [comment] 2020-04-18 20:06
yes bulding.obj is the last version, to test if it works, if it works then we'll do the cultural and park but we don't know yet if it s worth spending time on that. Can you visualize this one?

**Comment by RELNO** [comment] 2020-04-18 20:33
![Screen Shot 2020-04-18 at 16 31 25](https://user-images.githubusercontent.com/14296774/79670573-1245e400-8192-11ea-8ed0-04638247838e.png)

the city model cannot be loaded, it's either has corrupt edges or its scale is too large/small acceptable.  @agrignard @tnguyenh I again ask that we do a quick call on this as it's one of the last issues we need to solve before deployment

**Comment by tnguyenh** [comment] 2020-04-19 16:27
Hi Ariel, I started the process again from the start, to be sure that I didn't leave any problem at any step. What scale do you need ? Try those 4 .obj files. 2 are scales by 1/2000. Buildings_simple*.obj are without holes to see if the problem comes from that.

**Comment by agrignard** [comment] 2020-04-20 09:43
@RELNO if you can have a look at the new 4 files generated by @tnguyenh ?

 If it works that great, if not we will need to see how to manually (by playing with rot and postion on the three.js cde) aligned all of them. Especially Agents andCity are particuraly misaligned (https://github.com/CityScope/CSL_Paris/issues/3)

**Comment by RELNO** [comment] 2020-04-20 14:15
@agrignard I'm not sure which one you're referring to, there are multiple versions of the same file:
<img width="160" alt="Screen Shot 2020-04-20 at 10 13 15" src="https://user-images.githubusercontent.com/14296774/79761520-92ce2700-82ef-11ea-9306-b37876047d20.png">

@tnguyenh to save some time, can you please use https://threejs.org/editor/ to test the models? If it loads well (scale, shapes, location etc) in this editor, it will load well in the app

**Comment by agrignard** [comment] 2020-04-20 14:30
"""Hi Ariel, I started the process again from the start, to be sure that I didn't leave any problem at any step. What scale do you need ? Try those 4 .obj files. 2 are scales by 1/2000. Buildings_simple*.obj are without holes to see if the problem comes from that."""

so building_scaled is scaled (reduce to 1/2000) , building_simple is without hole and building is not scaled.  

I think you want to test first building.obj

@tnguyenh do you have the park also?

**Comment by RELNO** [comment] 2020-04-20 14:33
@agrignard if you test `buildings_scaled` on https://threejs.org/editor/  you'll see large offset. Then we should test it with other layers to see they all load at the same location

**Comment by agrignard** [comment] 2020-04-20 14:46
Not great indeed in the three.js tool

According to @tnguyenh it's ok in blender and in in the default windows .obj. So it seems that the export in blender is not compatible with the way Three.js is parsing it

**Comment by agrignard** [comment] 2020-04-20 14:49
building_simple.Obj seems to work ?
<img width="1518" alt="Screen Shot 2020-04-20 at 16 48 26" src="https://user-images.githubusercontent.com/3928502/79765432-e871f600-8326-11ea-89ce-6d04dd2b15c4.png">

**Comment by agrignard** [comment] 2020-04-20 14:56
waht about this one (.stl)?
https://github.com/CityScope/CSL_Paris/blob/master/ReChamp_Gama/includes/GIS/obj/buildings.stl

**Comment by RELNO** [comment] 2020-04-20 14:57
building_simple.Obj is ok, can you test how other layers fit on this one? If they fall in the right place/scale we can use that

**Comment by tnguyenh** [comment] 2020-04-20 14:59
Can you use stl ? It looks better... buildings.stl is working fine with your link, and has a better mesh than buildings_simple. you just need to scale it, rotate it and maybe translate it.

![image](https://user-images.githubusercontent.com/18676913/79766464-4f43df00-8328-11ea-952b-55ad85d426b5.png)

**Comment by RELNO** [comment] 2020-04-20 15:05
@tnguyenh thanks, before I rewrite my importer, can you please export the parks and culture and see if they fall in the right position as the city model?

**Comment by tnguyenh** [comment] 2020-04-20 16:23
It should be fine now, try the 5 .stl files. You may have to rotate by -90 along x axis, and scale it.

![image](https://user-images.githubusercontent.com/18676913/79775086-0134d880-8334-11ea-993d-855ad1fbf933.png)

**Comment by RELNO** [comment] 2020-04-21 01:35
@tnguyenh thanks -- I gave it a shot but I think we'll stop here.  It's simpler to hand fix the mismatching. 

- STL is internally parsed as a huge object (~190mb) so their effect on heap-mem is significant 
- STL has a different loading process and geometry handling which at this point will incur too much refactoring.
- the city STL has no building height z axis but only one height, see image 
![Screen Shot 2020-04-20 at 21 25 00](https://user-images.githubusercontent.com/14296774/79815334-7e6d4700-834e-11ea-90e5-36e2a503cefd.png)

**Comment by agrignard** [comment] 2020-04-21 08:36
Ok so do we align them by "hand" in the code? Looking at the deadline I think it's safer to do it by hans and the results might look the same

**Comment by tnguyenh** [comment] 2020-04-21 11:38
>     * the city STL has no building height z axis but only one height, see image
>       ![Screen Shot 2020-04-20 at 21 25 00](https://user-images.githubusercontent.com/14296774/79815334-7e6d4700-834e-11ea-90e5-36e2a503cefd.png)

Because you are looking upside down. Rotate by 180 and I think you will have the proper height.

**Comment by tnguyenh** [comment] 2020-04-21 19:48
Try the .obj. It is just a conversion from .stl to .obj, it's working fine on threejs website.

**Comment by RELNO** [comment] 2020-04-22 18:29
![Screen Shot 2020-04-22 at 14 28 43](https://user-images.githubusercontent.com/14296774/80019487-973c4080-84a5-11ea-8232-97f81b526feb.png)
no perfect but closer

**Comment by RELNO** [comment] 2020-04-22 18:29
will dive into the new stl/obj in the next version

**Comment by RELNO** [comment] 2020-05-26 19:04
we'll make it more streamlined next time. QGIS->Blender->JSON->THREE is a long trip...

**Closed as completed by RELNO** 2020-05-26 19:04 UTC
Labels: wontfix, ThreeJS, 3D Modeling, Deployment
